#!/bin/sh

#SBATCH --job-name="clip-3"
#SBATCH --partition=a100
#SBATCH --exclude=aisurrey25
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=100G
#SBATCH --time=0-30:00:00
#SBATCH -o slurm_logs/slurm.%N.%j.out 
#SBATCH -e slurm_logs/slurm.%N.%j.err

launcher=launch.sh

script=finetune.py
args="--batch_size 16 --lr 4e-4"

arguments="$launcher torchrun --nproc_per_node=1 --master_port=12347 $script $args"
apptainer exec docker://container-registry.surrey.ac.uk/shared-containers/sobhan-sqa bash $arguments > finetune-3.out