#!/bin/sh

#SBATCH --job-name="clip-3"
#SBATCH --partition=a100
#SBATCH --exclude=aisurrey25
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=100G
#SBATCH --time=0-30:00:00
#SBATCH -o slurm_logs/slurm.%N.%j.out 
#SBATCH -e slurm_logs/slurm.%N.%j.err

# Function to find an available port
find_available_port() {
    while true; do
        PORT=$(( (RANDOM % 10000) + 10000 ))  # Random port between 10000 and 19999
        (echo > /dev/tcp/127.0.0.1/$PORT) >/dev/null 2>&1 || break
    done
    echo $PORT
}

# Find an available port
PORT=$(find_available_port)

launcher=launch.sh

script=finetune.py
args="--batch_size 16 --lr 4e-4 --data_ver 2 --run_ver 3"

arguments="$launcher torchrun --nproc_per_node=1 --master_port=$PORT $script $args"
apptainer exec docker://container-registry.surrey.ac.uk/shared-containers/sobhan-sqa bash $arguments > finetune-3.out