data:
    lmdb_path: /home/sobhan/Documents/Datasets/Phoenix/lmdb
    max_length: 300
    labels: /home/sobhan/Documents/Code/MLLM/data/labels
model:
    I3D: /home/sobhan/Documents/Code/PSP/tmp/meinedgs_i3d.pth.tar
    tokenizer: /home/sobhan/Documents/Code/MBart_trimmed
    transformer: /home/sobhan/Documents/Code/MBart_trimmed
    resnet: /home/sobhan/Documents/Code/MLLM/ckpts/resnet18.pth
    embed_dim: 1024
    sign_proj: True
training:
    wandb: disabled # online or disabled
    scale_embedding: False
    ckpt_path: /home/sobhan/Documents/Code/MLLM/ckpts/best-epoch=076-val_loss=1.120.ckpt
    ckpt_path_best: /mnt/fast/nobackup/scratch4weeks/sa04359/MMSLT/run_2024-12-10_17-56-53/best-epoch=076-val_loss=1.120.ckpt
save:
    output: outputs
    csv: csv_outputs/