data:
    lmdb_path: /home/sobhan/Documents/Code/MLLM/desc
    lmdb_path_images: /home/sobhan/Documents/Code/LLaMA-Adapter/SQA-Lightning/src/sqa/data/lmdb
    max_length: 300
    labels: /home/sobhan/Documents/Code/MLLM/data/labels
model:
    tokenizer: /home/sobhan/Documents/Code/MLLM/MBart_trimmed
    transformer: /home/sobhan/Documents/Code/MLLM/MBart_trimmed
    resnet: /home/sobhan/Documents/Code/MLLM/ckpts/resnet18.pth
    embed_dim: 1024
    sign_proj: False
    alpha: 0.5
training:
    wandb: disabled # online or disabled
    scale_embedding: False
    ckpt_path: /mnt/fast/nobackup/scratch4weeks/sa04359/MMSLT/run_2024-12-13_19-20-52/best-epoch=053-val_loss=0.904.ckpt
    ckpt_path_best: /mnt/fast/nobackup/scratch4weeks/sa04359/MMSLT/run_2024-12-10_17-56-53/best-epoch=076-val_loss=1.120.ckpt
save:
    output: outputs/
    csv: csv_outputs/