data:
    lmdb_path: '/home/sobhan/Documents/Code/LLaMA-Adapter/SQA-Lightning/src/sqa/data/lmdb'
    max_length: 300
model:
    I3D: /home/sobhan/Documents/Code/PSP/tmp/meinedgs_i3d.pth.tar
    tokenizer: pretrain_models/MBart_trimmed
    transformer:  pretrain_models/MBart_trimmed
    visual_encoder: pretrain_models/mytran
    resnet: resnet18.pth
    embed_dim: 1024
    sign_proj: True
training:
    wandb: disabled # online or disabled
    scale_embedding: False
    ckpt_path: /home/sobhan/Documents/Code/MLLM/ckpts/best-epoch=020-val_loss=1.081.ckpt