data:
    lmdb_path: /home/sobhan/Documents/Datasets/csldaily/sentences/lmdbs/csldaily-lmdbs
    max_length: 300
    labels: /home/sobhan/Documents/Code/MLLM/data/csldaily/labels
    desc_path: /home/sobhan/Documents/Datasets/csldaily/Desc-Features
    hamer_path: /home/sobhan/Documents/Datasets/CSLDaily_HaMeR_lzma/
model:
    tokenizer: /home/sobhan/Documents/Weigths/MBart_trimmed_csldaily
    transformer: /home/sobhan/Documents/Weigths/MBart_trimmed_csldaily
    dino: /home/sobhan/Documents/Weigths/dino/tmp.pth
    embed_dim: 1024
    sign_proj: False
training:
    wandb: disabled # online or disabled
    scale_embedding: False
    ckpt_path: /home/sobhan/Documents/Code/MLLM/outputs/run_2025-04-04_14-33-27_landa_desc_1.0_landa_hamer_1.0_warmup_0.05/best-epoch=001-val_total_loss=1.773.ckpt
save:
    output: outputs/
    csv: csv_outputs/