channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - lightning==2.4.0
    - torchmetrics==1.4.1
    - sentencepiece==0.2.0
    - timm==1.0.8
    - transformers==4.32.0
    - torchvision==0.19.0
    - einops==0.8.0
    - humanize==4.10.0
    - hydra-core==1.3.2
    - pyyaml==6.0.1
    - regex==2024.7.24
    - pillow==10.4.0
    - vidaug==1.5
    - scikit-image==0.24.0
    - numpy==2.0.1
    - tqdm==4.66.5
    - wandb==0.18.0
    - scipy==1.14.0
    - seaborn==0.13.2
    - joblib==1.3.1
    - fastdtw==0.3.4
    - scipy==1.14.0
    - tokenizers==0.13.3 
    - jiwer==3.0.3 
    - fasttext==0.9.2
    - opencv-python==4.10.0.84  
    - pandas==2.2.2 
    - ffmpeg==1.4
    - lmdb==1.5.1
    - tensorboard==2.18.0
    - tensorboard-pytorch==0.7.1
    - sacrebleu==2.4.3
    - xformers
    - decord==0.6.0
    - peft==0.13.0